/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFundManager } from "../IFundManager";

export class IFundManager__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFundManager {
    return new Contract(address, _abi, signerOrProvider) as IFundManager;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getInterestFeesUnclaimed",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getRebalancerPercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdrawInterestFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
