/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface L2CheckpointContract
  extends Truffle.Contract<L2CheckpointInstance> {
  "new"(
    _minterMessenger: string,
    _l1Broker: string,
    meta?: Truffle.TransactionDetails
  ): Promise<L2CheckpointInstance>;
}

type AllEvents = never;

export interface L2CheckpointInstance extends Truffle.ContractInstance {
  l1Broker(txDetails?: Truffle.TransactionDetails): Promise<string>;

  minterMessenger(txDetails?: Truffle.TransactionDetails): Promise<string>;

  withdrawAndMint: {
    (
      l2Token: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      l2Token: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      l2Token: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      l2Token: string,
      amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    l1Broker(txDetails?: Truffle.TransactionDetails): Promise<string>;

    minterMessenger(txDetails?: Truffle.TransactionDetails): Promise<string>;

    withdrawAndMint: {
      (
        l2Token: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        l2Token: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        l2Token: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        l2Token: string,
        amount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
