name: Tests

on: [push, pull_request]

jobs:
  e2e-and-unit:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Run unit tests with coverage
        run: npm run coverage

      # - name: Upload coverage report to Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }} # This is passed by Github, don't worry about setting this.
